#!/usr/bin/env python3
"""Verify every URL on the live site resolves in the new site.

Checks each <loc> in the live sitemap against the built output in dist/ and
the rules in public/_redirects. A URL passes if it is either a built route or
matched by a redirect rule.

This is the guard on the IA consolidation: the flattened sitemap is only safe
because every retired URL still lands somewhere sensible. Run it after changing
routes or redirects.

Usage (from repo root):

    mise run verify

    python scripts/verify-redirects.py [--sitemap URL_OR_PATH]

Requires a build first (reads dist/). Standard library only.

Exit status is 0 when every URL resolves, 1 otherwise.


Generated by Claude Opus 5 (via Claude Code), reviewed by a human.
"""

from __future__ import annotations

import argparse
import re
import sys
import urllib.request
from pathlib import Path

DEFAULT_SITEMAP = "https://washcobikes.org/sitemap.xml"
ROOT = Path(__file__).resolve().parent.parent
SNAPSHOT = ROOT / "scripts" / "sitemap-snapshot.txt"
SNAPSHOT_HEADER = (
    f"# Snapshot of {DEFAULT_SITEMAP}, captured 2026-08-13.\n"
    "# CI checks redirect coverage against this fixed list so builds don't depend\n"
    "# on the live site being up. Refresh with:\n"
    "#   python3 scripts/verify-redirects.py --snapshot\n"
)


def load_sitemap(source: str) -> list[str]:
    """Return root-relative paths from a sitemap URL/file or a plain-text list.

    Accepts sitemap XML (any <loc> values) or the committed snapshot, which is
    one path per line with `#` comments.
    """
    if source.startswith(("http://", "https://")):
        with urllib.request.urlopen(source, timeout=30) as response:
            text = response.read().decode("utf-8", "replace")
    else:
        text = Path(source).read_text(encoding="utf-8", errors="replace")

    locs = re.findall(r"<loc>(.*?)</loc>", text, re.DOTALL)
    if not locs:
        locs = [
            line.strip()
            for line in text.splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        ]

    paths = set()
    for loc in locs:
        path = re.sub(r"^https?://[^/]+", "", loc.strip()).rstrip("/")
        paths.add(path or "/")
    return sorted(paths)


def load_routes(dist: Path) -> set[str]:
    """Return the routes present in the built output."""
    routes = set()
    for index in dist.rglob("index.html"):
        relative = index.parent.relative_to(dist).as_posix()
        routes.add("/" if relative == "." else "/" + relative)
    return routes


def load_rules(redirects: Path) -> list[tuple[str, str]]:
    """Return (source, target) pairs from a Netlify _redirects file."""
    rules = []
    for line in redirects.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        fields = line.split()
        if len(fields) >= 2:
            rules.append((fields[0].rstrip("/") or "/", fields[1]))
    return rules


def resolve(path: str, routes: set[str], rules: list[tuple[str, str]]) -> str | None:
    """Return how this path resolves, or None if nothing handles it."""
    if path in routes:
        return "route"
    for source, target in rules:
        if source == path:
            return f"redirect -> {target}"
        if source.endswith("/*") and path.startswith(source[:-2]):
            return f"splat -> {target}"
        if source.startswith("/*.") and path.endswith(source[2:]):
            return f"splat -> {target}"
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--sitemap",
        default=str(SNAPSHOT),
        help="sitemap URL or local path (default: the committed snapshot)",
    )
    parser.add_argument(
        "--live",
        action="store_true",
        help=f"check against {DEFAULT_SITEMAP} instead of the snapshot",
    )
    parser.add_argument(
        "--snapshot",
        action="store_true",
        help="refresh the committed snapshot from the live sitemap and exit",
    )
    args = parser.parse_args()

    if args.snapshot:
        paths = load_sitemap(DEFAULT_SITEMAP)
        SNAPSHOT.write_text(SNAPSHOT_HEADER + "\n".join(paths) + "\n", encoding="utf-8")
        print(f"Wrote {len(paths)} paths to {SNAPSHOT.relative_to(ROOT)}")
        return 0

    if args.live:
        args.sitemap = DEFAULT_SITEMAP

    dist = ROOT / "dist"
    if not dist.is_dir():
        print("dist/ not found — run `mise run build` first.", file=sys.stderr)
        return 1

    redirects = ROOT / "public" / "_redirects"
    if not redirects.is_file():
        print("public/_redirects not found.", file=sys.stderr)
        return 1

    paths = load_sitemap(args.sitemap)
    routes = load_routes(dist)
    rules = load_rules(redirects)

    unresolved = [path for path in paths if resolve(path, routes, rules) is None]

    print(
        f"{len(paths)} sitemap URLs "
        f"vs {len(routes)} built routes + {len(rules)} redirect rules"
    )

    if unresolved:
        print(f"\nUNRESOLVED ({len(unresolved)}):", file=sys.stderr)
        for path in unresolved:
            print(f"  {path}", file=sys.stderr)
        return 1

    print("All URLs resolve.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
